name: Deploy to AWS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Install dependencies
        run: npm install

      - name: Use Doppler
        uses: dopplerhq/cli-action@v2

      - name: Deploy to AWS Staging
        run: doppler run --config stg -- sls deploy --stage  staging
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN_STG }}

      - name: Deploy to AWS Prod
        run: doppler run -- sls deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
